# Curated references. Book names must match fetch.BOOKS. Verse spec: "ch:v" or "ch:v-v".
THEMES=[
 ("The LORD is slow to anger",
  "Before anything is said about our anger, Scripture describes God's. His anger is real, but it is slow, measured, and always paired with steadfast love. This is the pattern we are being restored to.",
  [("Exodus","34:6-7"),("Numbers","14:18"),("Psalms","30:5"),("Psalms","78:38"),("Psalms","86:15"),("Psalms","103:8-10"),("Psalms","145:8"),("Isaiah","54:7-8"),("Joel","2:13"),("Jonah","4:2"),("Micah","7:18"),("Nahum","1:2-3")]),
 ("God's righteous wrath — and rescue from it",
  "God's wrath is never a loss of control; it is his settled opposition to evil. The gospel is that Christ bore it for us.",
  [("Psalms","7:11"),("Nahum","1:6"),("John","3:36"),("Romans","1:18"),("Romans","2:5-8"),("Romans","5:8-9"),("Ephesians","2:3-5"),("Ephesians","5:6"),("Colossians","3:5-6"),("1 Thessalonians","1:10"),("1 Thessalonians","5:9")]),
 ("Wisdom on the hot temper",
  "Proverbs is the Bible's most practical anger-management course: what a quick temper costs, and what patience wins.",
  [("Job","5:2"),("Psalms","37:8"),("Proverbs","12:16"),("Proverbs","14:17"),("Proverbs","14:29"),("Proverbs","15:1"),("Proverbs","15:18"),("Proverbs","16:32"),("Proverbs","17:14"),("Proverbs","19:11"),("Proverbs","19:19"),("Proverbs","20:3"),("Proverbs","22:24-25"),("Proverbs","25:28"),("Proverbs","27:4"),("Proverbs","29:8"),("Proverbs","29:11"),("Proverbs","29:22"),("Proverbs","30:33"),("Ecclesiastes","7:9")]),
 ("Jesus on anger",
  "Jesus moves anger from the courtroom to the heart: the problem is not only the blow but the contempt behind it, and the remedy is reconciliation before worship.",
  [("Matthew","5:21-26"),("Matthew","5:38-48"),("Matthew","15:18-20"),("Luke","6:27-36"),("Luke","6:45")]),
 ("The apostles on anger",
  "The letters assume Christians will feel anger. The instruction is about what to do with it before the sun goes down.",
  [("Psalms","4:4-5"),("Romans","12:17-21"),("1 Corinthians","13:4-7"),("2 Corinthians","12:20"),("Galatians","5:19-23"),("Ephesians","4:26-27"),("Ephesians","4:29-32"),("Colossians","3:8"),("Colossians","3:12-15"),("1 Timothy","2:8"),("Titus","1:7"),("Hebrews","12:14-15"),("James","1:19-21"),("James","3:5-10"),("James","4:1-3"),("1 Peter","2:21-23"),("1 Peter","3:8-9")]),
 ("Leave room for God's justice",
  "Much of our anger is really a demand for vengeance. Scripture does not say the wrong doesn't matter; it says the settling of accounts belongs to God.",
  [("Leviticus","19:17-18"),("Deuteronomy","32:35"),("Proverbs","20:22"),("Proverbs","24:17-18"),("Proverbs","24:29"),("1 Thessalonians","5:15")]),
 ("Anger in the home",
  "Where anger does the most damage, and where the Word is most specific about fathers, husbands and the words spoken under one roof.",
  [("Genesis","49:5-7"),("Proverbs","21:9"),("Proverbs","21:19"),("Ephesians","6:4"),("Colossians","3:19-21")]),
 ("Forgiveness and reconciliation",
  "The way out of anger is not suppression but forgiveness — received first, then given.",
  [("Proverbs","10:12"),("Proverbs","17:9"),("Matthew","6:12-15"),("Matthew","18:15"),("Luke","17:3-4"),("Romans","12:18"),("1 Peter","4:8")]),
 ("Prayers for the angry and the hurting",
  "The Psalms give words to anger rather than hiding it — and then turn it toward God. Useful as opening or closing readings for a session.",
  [("Psalms","13:1-6"),("Psalms","37:7-9"),("Psalms","51:10"),("Psalms","73:21-26"),("Psalms","139:23-24"),("Lamentations","3:19-26"),("Habakkuk","1:2-4")]),
]

# (title, book, passage range, summary, [quoted ranges], what it shows)
STORIES=[
 ("Cain and Abel","Genesis","4:1-16",
  "The first anger in the Bible. Cain's offering is not regarded, his face falls, and God comes to him before anything has happened: sin is crouching at the door, and Cain can rule over it. He does not. He invites his brother into the field and kills him.",
  ["4:3-8"],"God addresses the anger before the act. Anger unmastered becomes murder; anger named and ruled does not."),
 ("Esau's grudge, and the embrace","Genesis","27:41-45; 33:1-11",
  "Cheated of the blessing, Esau plans to kill Jacob once their father has died; Rebekah sends Jacob away until his brother's fury turns. Twenty years later Esau runs to meet him, embraces him, and weeps.",
  ["27:41-45","33:1-4"],"Anger held as a plan for revenge — and how time, distance and God's work in both men dissolved it."),
 ("Simeon and Levi at Shechem","Genesis","34:1-31; 49:5-7",
  "After their sister Dinah is violated, Simeon and Levi deceive the men of Shechem and slaughter the city. Their anger was understandable; their vengeance was not. On his deathbed Jacob curses that anger rather than blessing the two sons.",
  ["34:25-31","49:5-7"],"Righteous grievance turned into indiscriminate revenge — and its long shadow over a family."),
 ("Joseph and his brothers","Genesis","37:3-28; 45:1-15; 50:15-21",
  "Jealousy hardens into hatred; the brothers cannot speak peaceably to Joseph and finally sell him. Decades later, with every reason for revenge, Joseph weeps, forgives, and reframes the whole story: you meant evil, God meant good.",
  ["37:3-4","45:4-8","50:15-21"],"The fullest picture in Genesis of anger's opposite: forgiveness that provides for the offender."),
 ("Moses kills the Egyptian","Exodus","2:11-15",
  "Seeing a Hebrew beaten, Moses looks both ways and strikes the Egyptian dead. The next day his own people throw it back at him, and he flees to Midian for forty years.",
  ["2:11-15"],"Anger at real injustice, acted on in secret and by force, costs Moses everything for a generation."),
 ("Moses and the golden calf","Exodus","32:7-14, 19-20",
  "God's anger burns against Israel and Moses pleads for them — then Moses comes down the mountain, sees the calf, and his own anger burns hot: he shatters the tablets and grinds the idol to powder.",
  ["32:9-14","32:19-20"],"Two angers in one chapter: God's, which Moses intercedes against, and Moses' own, which is hot but aimed at the sin."),
 ("Moses strikes the rock","Numbers","20:2-13; Psalm 106:32-33; Deuteronomy 34:1-5",
  "The people quarrel for water again. God tells Moses to speak to the rock. Moses calls them rebels and strikes it twice. Water comes — but Moses and Aaron are told they will not bring the people into the land. The psalm names what happened: they made his spirit bitter, and he spoke rashly with his lips. Moses later sees the land from Mount Nebo but does not enter it.",
  ["20:7-12"],"A lifetime of faithfulness, and one rash, angry act at the end still carried a consequence. Provocation is real, but it does not excuse the response.",
  [("Psalms","106:32-33"),("Deuteronomy","34:4-5")]),
 ("Balaam beats his donkey","Numbers","22:21-35",
  "Three times the donkey turns aside from the angel Balaam cannot see, and three times Balaam strikes her in anger. When the donkey speaks, the absurdity is exposed: he was raging at the one thing saving his life.",
  ["22:27-33"],"Anger blinds. Balaam's fury at the animal kept him from seeing what was actually in the road."),
 ("Samson's cycle of retaliation","Judges","14:19-20; 15:1-8",
  "Humiliated at his own wedding feast, Samson kills thirty men in hot anger and walks out. When he returns his wife has been given away; he burns the Philistines' harvest; they burn her and her father; he strikes them again. Each side calls it justice.",
  ["14:19-20","15:3-8"],"The escalation spiral: every act of anger 'only' answers the last one, and no one can stop."),
 ("Saul's jealousy turns to rage","1 Samuel","18:6-11; 20:30-34",
  "The women sing that David has slain his ten thousands, and Saul is very angry; the next day he hurls a spear at David. Later his anger turns on his own son Jonathan for defending David.",
  ["18:6-11","20:30-34"],"Anger fed by envy and insecurity, ending in violence toward the people closest to him."),
 ("David, Nabal and Abigail","1 Samuel","25:2-35",
  "Insulted by Nabal, David straps on his sword and sets out to kill every male in the house. Abigail meets him on the road with food, humility and plain truth. David blesses her for keeping him from bloodguilt and from working salvation with his own hand.",
  ["25:21-26","25:32-35"],"The clearest picture in Scripture of anger being talked down. A wise word, delivered in time, changed the outcome."),
 ("Nathan confronts David","2 Samuel","12:1-7",
  "Nathan tells the king a story about a rich man who took a poor man's one lamb. David's anger is greatly kindled against the man — and Nathan says, 'You are the man.'",
  ["12:1-7"],"How easily our anger is aimed outward at the very sin we are living in."),
 ("Absalom's two-year silence","2 Samuel","13:20-29",
  "After Amnon violates Tamar, David is very angry but does nothing. Absalom says nothing to Amnon, good or bad — and hates him. Two years later he has him killed at a feast.",
  ["13:20-23","13:28-29"],"Unspoken anger does not fade; it waits. A father's passivity and a brother's nursed hatred both end in death."),
 ("Ahab sulks over a vineyard","1 Kings","21:1-16",
  "Naboth will not sell his inheritance. Ahab goes home vexed and sullen, lies on his bed and refuses to eat. Jezebel takes over, and Naboth is stoned on false charges.",
  ["21:1-7"],"Anger that turns inward as sulking still finds a way out — here, through someone willing to act on it."),
 ("Naaman goes away in a rage","2 Kings","5:9-14",
  "The Syrian commander expects a ceremony and is told to wash in the Jordan. He turns and goes away in a rage. His servants reason with him; he goes down into the river and is healed.",
  ["5:9-14"],"Wounded pride dressed up as anger, and healing that came only after he listened."),
 ("King Asa and the seer","2 Chronicles","16:7-10",
  "Rebuked by the prophet Hanani for relying on Syria rather than God, Asa is in a rage, puts the seer in the stocks and inflicts cruelties on the people.",
  ["16:7-10"],"Anger as a reaction to correction — the hardest kind to admit."),
 ("Uzziah in the temple","2 Chronicles","26:16-21",
  "Strong and proud, Uzziah enters the temple to burn incense himself. When the priests withstand him he becomes angry, censer in hand — and leprosy breaks out on his forehead.",
  ["26:16-21"],"Pride, then anger at being told no; the consequence followed him the rest of his life."),
 ("Nehemiah takes counsel with himself","Nehemiah","5:1-13",
  "Hearing that the nobles are charging interest and enslaving their own people, Nehemiah is very angry. Then the key sentence: he takes counsel with himself, and only then brings charges and calls a public assembly. The wrong is put right.",
  ["5:6-13"],"The Bible's best model of anger used well: felt fully, paused, then channeled into a just and public remedy."),
 ("Haman's fury","Esther","3:5-6; 5:9-14",
  "Mordecai will not bow, and Haman is filled with fury — so much that destroying one man is not enough; he plots the destruction of a whole people. His wife and friends feed it: build a gallows.",
  ["3:5-6","5:9-14"],"Fury magnified by pride and by the company that encourages it. It ends on Haman's own gallows."),
 ("Jonah: 'Do you do well to be angry?'","Jonah","4:1-11",
  "Nineveh repents and Jonah is furious — angry enough to die — because God is gracious to the wrong people. God asks him the same question twice, and answers it with a plant.",
  ["4:1-4","4:9-11"],"Anger at grace shown to others; and God's gentle, persistent questioning of it."),
 ("Nebuchadnezzar's furious rage","Daniel","3:13-19, 24-28",
  "The king is in a furious rage that three men will not bow; his face changes and he orders the furnace heated seven times over. In the fire, a fourth figure. The king who raged ends up blessing their God.",
  ["3:13-19"],"The rage of power when it is defied — and its powerlessness before God."),
 ("Herod and the children of Bethlehem","Matthew","2:16-18",
  "Tricked by the wise men, Herod becomes furious and kills every boy in Bethlehem two years old and under.",
  ["2:16-18"],"Anger with unchecked power behind it is the most dangerous anger in Scripture."),
 ("The synagogue at Nazareth","Luke","4:24-30",
  "Jesus reminds his hometown that God's grace went to a widow in Sidon and a Syrian leper. All in the synagogue are filled with wrath and drive him to the cliff's edge.",
  ["4:24-30"],"Religious anger at the reach of grace — the same anger as Jonah's, now aimed at Jesus."),
 ("Jesus angry in the synagogue","Mark","3:1-6",
  "A man with a withered hand; watchers waiting to accuse. Jesus looks around at them with anger, grieved at their hardness of heart, heals the man — and they go out to plot his death.",
  ["3:1-6"],"Jesus' anger: aimed at hardness of heart, mixed with grief, and expressed as an act of mercy. This is the model of righteous anger."),
 ("Jesus clears the temple","John","2:13-17",
  "Jesus makes a whip of cords and drives out the animals and the money-changers: 'Do not make my Father's house a house of trade.' His disciples remember, 'Zeal for your house will consume me.'",
  ["2:13-17"],"Zeal for God's honour, deliberate (he made the whip), directed at exploitation — not at people who had wronged him personally."),
 ("James and John want fire from heaven","Luke","9:51-56",
  "A Samaritan village refuses Jesus. James and John ask if they should call down fire. Jesus turns and rebukes them, and they go to another village.",
  ["9:51-56"],"Zeal for Jesus is not the same as the Spirit of Jesus. He rebukes the anger, not the villagers."),
 ("The unforgiving servant","Matthew","18:21-35",
  "Forgiven a debt he could never pay, a servant seizes a fellow servant by the throat over a small one. His master, in anger, hands him over — 'So also my heavenly Father will do to every one of you, if you do not forgive your brother from your heart.'",
  ["18:21-22","18:28-35"],"Jesus ties our anger toward others directly to how much we have grasped of our own forgiveness."),
 ("The older brother","Luke","15:25-32",
  "The prodigal comes home to a feast; the older brother hears the music, becomes angry and refuses to go in. The father comes out to him too, and the story ends without telling us whether he went in.",
  ["15:25-32"],"The anger of the faithful when grace seems unfair. The father pleads rather than scolds."),
 ("Peter draws the sword","John","18:10-11",
  "In the garden Peter strikes the high priest's servant and cuts off his ear. Jesus: 'Put your sword into its sheath; shall I not drink the cup that the Father has given me?' Luke adds that Jesus healed the ear.",
  ["18:10-11"],"Loyal anger, instant and physical; and Jesus undoing its damage.",
  [("Luke","22:49-51")]),
 ("The stoning of Stephen","Acts","7:54-60",
  "Hearing Stephen's sermon, the council is enraged and grinds their teeth; they stop their ears, rush at him and stone him. Stephen dies praying, 'Lord, do not hold this sin against them.'",
  ["7:54-60"],"Two responses to the same moment: a mob's rage, and a man's forgiveness with his last breath."),
 ("Paul and Barnabas part ways","Acts","15:36-41",
  "Over whether to take John Mark, there is a sharp disagreement — sharp enough that they separate. Later letters show the breach healed: Paul asks for Mark, 'for he is very useful to me.'",
  ["15:36-41"],"Anger between good people over a real difference; separation for a season, and reconciliation later.",
  [("2 Timothy","4:11")]),
 ("The riot in Ephesus","Acts","19:23-41",
  "Demetrius the silversmith stirs up the craftsmen, and the city is in confusion: two hours of shouting, most of them not knowing why they had come. The town clerk quiets the crowd with plain reasoning and sends them home.",
  ["19:28-32","19:35-41"],"Crowd anger: contagious, largely uninformed, and calmed by a steady voice that names the facts."),
]

CONCORDANCE_WORDS=["anger","angered","angers","angry","wrath","wrathful","fury","furious","rage","raged","rages","raging","enraged","indignation","indignant","provoke","provoked","provokes","provoking","temper","hot-tempered","quick-tempered"]
